### ISSUE TITLE
setup.py to allow PIP-based installation

### ISSUE THREAD

**Issue by davidstrauss** [shaunlee/LevelDB-Shell#1]
This is a neat utility, but it'd be a lot easier to install for Python if there were a proper setup.py in the root of the repository.

I'm happy to make one if you're interested.

**Comment by shaunlee** [comment]
Yes, please

**Comment by davidstrauss** [comment]
Done. I've also updated the README with new installation and usage instructions. If you like, you can switch it back to using "ldb" or "ldb.py" as the executable, but "leveldb-shell" is preferable for something using PIP that installs into the global bin path.

If you're an Ubuntu user, can you give the new instructions a test? I have only tested the Fedora PIP instructions. The Ubuntu ones should either work or require only small changes to the apt-get line.

**Comment by shaunlee** [comment]
That's great. I've tested on Ubuntu, and it works very well.
